version: "3.1"
services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
      - ./mongo/init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      TZ: Asia/Tokyo
volumes:
  mongo:
