version: "3.1"
services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
      - ./mongo/init:/docker-entrypoint-initdb.d
      - ./mongo/init-replset-cluster.js:/init-replset-cluster.js
    environment:
      TZ: Asia/Tokyo
    command: mongod --bind_ip_all --replSet rs0
volumes:
  mongo:
