version: 2.1

executors:
  default:
    working_directory: ~/project
    docker:
      - image: circleci/ruby:3.0.1-buster-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
      - image: mongo:4.4
        command: mongod --port 27017 --replSet rs0

orbs:
  ruby: circleci/ruby@1.0
  node: circleci/node@2

jobs:
  build:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./*

  test:
    executor: default
    steps:
      - attach_workspace:
          at: ~/project
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run: |
          sudo apt update
          sudo apt -y install gnupg2
          wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
          echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main" | sudo tee /etc/apt/sources.list.d/mongodb-org.list
          sudo apt update
          sudo apt-get install -y mongodb-org-shell
          mongo --host localhost:27017 \<<EOF
            var cfg = {
                "_id": "rs0",
                "members": [
                    {
                        "_id": 0,
                        "host": "localhost:27017",
                    }
                ]
            };
            rs.initiate(cfg, { force: true });
          EOF
      - run: bundle exec rspec
      - store_test_results:
          path: tmp/test_results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
