version: 2.1

executors:
  default:
    working_directory: ~/project
    docker:
      - image: circleci/ruby:3.0.1-buster-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
      - image: mongo:4.4
        command: mongod --port 27017 --replSet rs0

orbs:
  ruby: circleci/ruby@1.0
  node: circleci/node@2

jobs:
  build:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./*

  test:
    executor: default
    steps:
      - attach_workspace:
          at: ~/project
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run: bundle exec rspec
      - store_test_results:
          path: tmp/test_results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
